### ISSUE TITLE
(psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above

### ISSUE THREAD

**Issue by burakince** [burakince/mlflow#1]
**Describe the bug**

When we try to use mlflow docker image on arm64 architecture with Postgres connection, the driver returns the following error.

```
(psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above
```

**To Reproduce**

1. Run the image on arm64 machine with PostgreSQL connection settings.
2. Look up to starting logs
3. See error

**Expected behavior**

It must start to connect PostgreSQL database.

** Tested system:**

 - Architecture: arm64 (Raspberry Pi)
 - Cluster: Kubernetes 1.23.5
 - Mlflow Docker Image Version: 1.27.0.9

**Additional context**

You can find more information from [this issue](https://github.com/psycopg/psycopg2/issues/1360).

**Comment by burakince** [comment]
THe solution looks like usage of [psycopg3](https://www.psycopg.org/psycopg3/) driver. But latest version of sqlalchemy (1.4.39) doesn't not support **psycopg** dialect. It's part of the milestone 2.0 for the sqlalchemy.

**Comment by ecederstrand** [comment]
@burakince I stumbled into this issue today. Is there a workaround? The linux/arm64 images at https://hub.docker.com/r/burakince/mlflow/tags don't seem to work for me either.

**Comment by burakince** [comment]
Hi @ecederstrand ,

Sorry for the late response. You can use Mysql for your DB backend. It works fine on the arm64 arch. Unfortunately, I don't know any other workaround for this issue. :(

Best,
Burak

**Comment by burakince** [comment]
I have tested the latest version on my Raspberry Pi-based Kubernetes cluster using PostgreSQL 15, and it works as expected with PostgreSQL 15 or later. I recommend using the latest MLflow image version along with PostgreSQL 15 or a higher major version.

As the issue appears resolved, I am closing it. If you continue to encounter any problems, please feel free to reopen the issue.
